spring:
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        auto_quote_keyword: true
        show_sql: true
        id:
          sequence:
            increment_size_mismatch_strategy: FIX
  application:
    name: admin3
  datasource:
    url: jdbc:oracle:thin:@selforaclecloudatp_high
    username: admin3
    password: 1qaz@WSX#EDC
  sql:
    init:
      encoding: utf8
      data-locations: classpath:data.sql
      mode: never
      continue-on-error: true
  data:
    web:
      pageable:
        one-indexed-parameters: true
    redis:
      database: 0
      host: 192.168.192.173
      port: 16379
  profiles:
    include: biz
server:
  servlet:
    context-path: /admin3
app:
  oxr:
    id: OXR_APP_ID
# keytool -importcert -alias GglMySQLCACert -file server-ca.pem \ -keystore truststore -storepass 1qaz@WSX
