spring:
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        auto_quote_keyword: true
        show_sql: true
        id:
          sequence:
            increment_size_mismatch_strategy: FIX
  application:
    name: admin3
  sql:
    init:
      encoding: utf8
      data-locations: classpath:data.sql
      mode: never
      continue-on-error: true
  datasource:
    url: jdbc:oracle:thin:admin3@locahost:1521:xe
    username: admin3
    password: your_password
  data:
    web:
      pageable:
        one-indexed-parameters: true
    redis:
      database: 0
      host: localhost
      port: 6379
      password: your_password
  profiles:
    include: biz
server:
  servlet:
    context-path: /admin3
logging:
  file:
    name: logs/admin3.log            # 设置日志文件的名称
  logback:
    rollingpolicy:
      max-history: 30
