CREATE TABLE TB_ROLE
(	"ID" NUMBER(19,0) PRIMARY KEY NOT NULL,
   "AVAILABLE" NUMBER(1,0),
   "DESCRIPTION" VARCHAR2(255 CHAR),
   "NAME" VARCHAR2(255) NOT NULL UNIQUE,
   CHECK ("AVAILABLE" in (0,1)) ENABLE
);


CREATE TABLE "TB_STORAGE_CONFIG"
(
  "ID" NUMBER(19,0) PRIMARY KEY NOT NULL,
  "DEFAULT_FLAG" NUMBER(1,0) NOT NULL,
  "TYPE" NUMBER(3,0),
  "CREATE_TIME" TIMESTAMP (6),
  "ACCESS_KEY" VARCHAR2(255 CHAR),
  "ADDRESS" VARCHAR2(255 CHAR),
  "BUCKET_NAME" VARCHAR2(255 CHAR),
  "CREATE_USER" VARCHAR2(255 CHAR),
  "ENDPOINT" VARCHAR2(255 CHAR),
  "NAME" VARCHAR2(255 CHAR),
  "SECRET_KEY" VARCHAR2(255 CHAR),
  "STORAGE_ID" VARCHAR2(255 CHAR) NOT NULL UNIQUE,
  "STORAGE_PATH" VARCHAR2(255 CHAR),
  "REGION" VARCHAR2(255 CHAR),
  "EXTRA_CONFIG_JSON" VARCHAR2(2000),
  CHECK ("DEFAULT_FLAG" in (0,1)) ENABLE
);


CREATE TABLE "TB_STORAGE_FILE"
(
  "ID" NUMBER(19,0) PRIMARY KEY NOT NULL ,
  "CREATE_TIME" TIMESTAMP (6),
   "size" NUMBER(12,0),
   "CREATE_USER" VARCHAR2(255 CHAR),
   "key" VARCHAR2(255 CHAR) UNIQUE NOT NULL,
   "NAME" VARCHAR2(255 CHAR),
   "STORAGE_ID" VARCHAR2(255 CHAR),
   "type" VARCHAR2(255 CHAR)
);


CREATE TABLE "TB_ORGANIZATION"
(
  "ID" NUMBER(19,0) PRIMARY KEY NOT NULL ,
   "TYPE" NUMBER(3,0) NOT NULL ENABLE,
   "PARENT_ID" NUMBER(19,0),
   "NAME" VARCHAR2(255 CHAR) UNIQUE NOT NULL ENABLE,
   "PARENT_IDS" VARCHAR2(255 CHAR),
   CHECK ("TYPE" between 0 and 1) ENABLE
);


CREATE TABLE "TB_RESOURCE"
(
   "ID" NUMBER(19,0) PRIMARY KEY NOT NULL,
   "TYPE" NUMBER(3,0),
   "PARENT_ID" NUMBER(19,0),
   "ICON" VARCHAR2(255 CHAR),
   "NAME" VARCHAR2(255 CHAR),
   "PARENT_IDS" VARCHAR2(255 CHAR),
   "PERMISSION" VARCHAR2(255 CHAR),
   "URL" VARCHAR2(255 CHAR),
   CHECK ("TYPE" between 0 and 1) ENABLE
);


CREATE TABLE "TB_ROLE_RESOURCE"
(	"RESOURCE_ID" NUMBER(19,0) NOT NULL ENABLE,
   "ROLE_ID" NUMBER(19,0) NOT NULL ENABLE,
   PRIMARY KEY ("RESOURCE_ID", "ROLE_ID")
);


CREATE TABLE "TB_USER"
(
  "ID" NUMBER(19,0) PRIMARY KEY NOT NULL ENABLE,
  "USERNAME" VARCHAR2(255 CHAR) UNIQUE NOT NULL ENABLE,
  "GENDER" NUMBER(3,0) NOT NULL ENABLE,
   "STATE" NUMBER(3,0) NOT NULL ENABLE,
   "CREATED_TIME" TIMESTAMP (6),
   "ORGANIZATION_ID" NUMBER(19,0),
   "AVATAR" VARCHAR2(255 CHAR),
   CHECK ("GENDER" between 0 and 1) ENABLE,
   CHECK ("STATE" between 0 and 1) ENABLE
);


CREATE TABLE "TB_USER_CREDENTIAL"
(	"IDENTITY_TYPE" NUMBER(3,0),
   "ID" NUMBER(19,0) PRIMARY KEY NOT NULL ENABLE,
   "USER_ID" NUMBER(19,0),
   "CREDENTIAL" VARCHAR2(255 CHAR) NOT NULL ENABLE,
   "IDENTIFIER" VARCHAR2(255 CHAR) NOT NULL ENABLE,
   CHECK (identity_type between 0 and 0) ENABLE
);

CREATE TABLE "TB_USER_ROLE"
(	"ROLE_ID" NUMBER(19,0) NOT NULL ENABLE,
   "USER_ID" NUMBER(19,0) NOT NULL ENABLE,
   PRIMARY KEY ("ROLE_ID", "USER_ID") ENABLE
);

CREATE TABLE "TB_SESSION"
(
  "ID" NUMBER(19,0) PRIMARY KEY NOT NULL ENABLE,
  "CREDENTIAL_ID" NUMBER(19,0),
  "EXPIRE_TIME" TIMESTAMP (6) NOT NULL ENABLE,
  "LAST_LOGIN_TIME" TIMESTAMP (6) NOT NULL ENABLE,
  "LAST_MODIFIED_TIME" TIMESTAMP (6),
  "TOKEN" VARCHAR2(255 CHAR) UNIQUE NOT NULL ENABLE,
  "DATA" CLOB
) ;


CREATE TABLE "TB_STORED_EVENT"
(	"ID" NUMBER(19,0) PRIMARY KEY NOT NULL ENABLE,
   "OCCURRED_ON" TIMESTAMP (6),
   "USER_ID" NUMBER(19,0) NOT NULL,
   "TYPE_NAME" VARCHAR2(255 CHAR),
   "EVENT_BODY" CLOB
);

CREATE SEQUENCE SEQ_ORGANIZATION INCREMENT BY 1 START WITH 2000;
CREATE SEQUENCE SEQ_RESOURCE INCREMENT BY 1 START WITH 2000;
CREATE SEQUENCE SEQ_ROLE INCREMENT BY 1 START WITH 2000;
CREATE SEQUENCE SEQ_SESSION INCREMENT BY 1 START WITH 2000;
CREATE SEQUENCE SEQ_STORAGE_CONFIG INCREMENT BY 1 START WITH 2000;
CREATE SEQUENCE SEQ_STORAGE_FILE INCREMENT BY 1 START WITH 2000;
CREATE SEQUENCE SEQ_STORED_EVENT INCREMENT BY 1 START WITH 2000;
CREATE SEQUENCE SEQ_USER_CREDENTIAL INCREMENT BY 1 START WITH 2000;
CREATE SEQUENCE SEQ_USER INCREMENT BY 1 START WITH 2000;
